services:
  caddy:
    image: caddy:latest
    volumes:
      # Mount the application code for live updates
      - ../:/var/www
      # Mount the Caddy configuration file
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # Mount the caddy data directory for cert storage
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # Map port 80 for HTTP
      - "80:80"
      # Map port 443 for HTTPS
      - "443:443"
    environment:
      - CADDY_ADMIN=:2019
    networks:
      - laravel-development
    depends_on:
      laravel:
        condition: service_started # Wait for laravel to start

  postgres:
    image: postgres:17
    restart: on-failure
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel-development

  laravel:
    # For the workspace service, we will also create a custom image to install and setup all the necessary stuff.
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true # Enables an interactive terminal
    stdin_open: true # Keeps standard input open for 'docker exec'
    env_file:
      - ../.env
    volumes:
      - ../:/var/www
      - ./php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
    ports:
      # Laravel development server
      - "8000:8000"
      # Vite development server
      - "5173:5173"
    networks:
      - laravel-development
    depends_on:
      postgres:
        condition: service_started # Wait for postgres to start
    command: composer run dev

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  laravel-development:
